# Generated by Django 4.2.6 on 2023-11-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Market_App', '0002_remove_product_brand_remove_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packing_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
